//
//  DriveMode.swift
//  DriverStats
//

import SwiftUI

enum DriveMode: Int, CaseIterable {
    case normal        = 0
    case offroad       = 1
    case racing        = 2
    case autoGenerated = 3

    var label: String {
        switch self {
        case .normal:        return "Normal"
        case .offroad:       return "Off-Road"
        case .racing:        return "Racing"
        case .autoGenerated: return "Auto-Generated"
        }
    }

    var sfSymbol: String {
        switch self {
        case .normal:        return "car.fill"
        case .offroad:       return "mountain.2.fill"
        case .racing:        return "flag.checkered"
        case .autoGenerated: return "wand.and.stars"
        }
    }

    var color: Color {
        switch self {
        case .normal:        return .blue
        case .offroad:       return .brown
        case .racing:        return .teal
        case .autoGenerated: return .purple
        }
    }

    var uiColor: UIColor {
        switch self {
        case .normal:        return .systemBlue
        case .offroad:       return UIColor(red: 0.59, green: 0.40, blue: 0.19, alpha: 1)
        case .racing:        return .systemTeal
        case .autoGenerated: return .systemPurple
        }
    }

    // Auto-generated connecting drives don't receive a smoothness score
    var receivesScore: Bool { self != .autoGenerated }
}
